name: "Send a Slack Message"
author: Tim Preece
description: Send message to slack
inputs:
  slack_webhook:
    description: "Slack webhook url"
    required: true
  message:
    description: "Message to send to slack channel"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.slack_webhook }}
    - ${{ inputs.message }}
