name: actions

on: push

jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/issue
        id: issue
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Test issue title
          body: Test issue body
          # assignees: "mrdoodles" #  line seperated
          assignees: |
            mrdoodles

      - run: |
          echo ${{ steps.issue.outputs.issue }}

      - uses: ./.github/actions/hello-docker
        id: hello
        with:
          who-to-greet: "Mr Doodles"

      - run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
          echo $HELLO
