name: Develop PR

on:
  pull_request:
    branches: [develop]

jobs:
  develop-pr-info:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - run: echo "WORKFLOW             ${{ github.workflow }}"
      - run: echo "GITHUB_EVENT_NAME    ${{ github.event_name }}"
      - run: echo "GITHUB_EVENT_PATH    ${{ github.event_path }}"
      - run: echo "GITHUB_HEAD_REF      ${{ github.head_ref }}"
      - run: echo "GITHUB_JOB           ${{ github.job }}"
      - run: echo "GITHUB_REF           ${{ github.ref }}"
      - run: echo "GITHUB_REF_NAME      ${{ github.ref_name }}"
      - run: echo "GITHUB_REF_PROTECTED ${{ github.ref_protected }}"
      - run: echo "GITHUB_REF_TYPE      ${{ github.ref_type }}"

      # - uses: actions/checkout@v2
      # - name: payload

      #   run: echo "${{ github.event.client_payload.env }}"
      # - name: List files
      #   run: |
      #     pwd
      #     ls -a
      #     echo $GITHUB_SHA
      #     echo $GITHUB_REPOSITORY
      #     echo $GITHUB_WORKSPACE
      #     echo "${{ github.token }}"
      #     # git clone git@github:$GIT_REPOSITORY
      #     # git checkout $GITHUB_SHA

  validate-code:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - run: npm ci
      - run: npm run format:check
      - run: npm test -- --coverage
        env:
          CI: true

      - name: Upload Test Coverage
        uses: actions/upload-artifact@v1
        with:
          path: coverage
          name: code-coverage
